"""empty_team_bots — a SourceMod plugin that fills an empty CS:S team with bots."""

module(
    name = "empty_team_bots",
    version = "1.1",
)

bazel_dep(name = "bazel_skylib", version = "1.9.2")
bazel_dep(name = "rules_sourcemod", version = "1.0.0")

git_override(
    module_name = "rules_sourcemod",
    commit = "257d1e9d166591fb768ac6ae480d28f9c5ec328d",
    remote = "https://github.com/kleinpa/rules_sourcemod.git",
)
